name: Deploy su Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy su Railway
        run: |
          curl -X POST "https://railway.app/deploy" \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}"
